import os

HOGWARTS_MAIN_TABLE_NAME = os.environ["HOGWARTS_MAIN_TABLE_NAME"]

AXIOS_CUSTOMER_ID = os.environ["AXIOS_CUSTOMER_ID"]
AXIOS_USERNAME = os.environ["AXIOS_USERNAME"]
AXIOS_PASSWORD = os.environ["AXIOS_PASSWORD"]

TELEGRAM_TOKEN = os.environ["TELEGRAM_TOKEN"]
TELEGRAM_GROUP_CHAT_ID = os.environ["TELEGRAM_GROUP_CHAT_ID"]
